// <auto-generated />
namespace RangementCarte.Migrations.CardRangement
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addTableCarte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableCarte));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111324341_addTableCarte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
